### ISSUE TITLE
API Endpoints all return 404s

### ISSUE THREAD

**Issue by BCWilsonDotCom** [alerta/docker-alerta#1]
Seems like this is missing something as none of the api endpoints seem to exist.

/# docker ps
CONTAINER ID        IMAGE                      COMMAND                CREATED             STATUS              PORTS                NAMES
d1525bedbd9c        alerta/alerta-web:latest   "/bin/sh -c '/config   3 minutes ago       Up 30 minutes        0.0.0.0:80->80/tcp   alerta-web
b40d673bc3ff        mongo:latest               "/entrypoint.sh mong   4 minutes ago       Up 36 minutes        27017/tcp            alerta-db

/# ENDPOINT=${1:-http://localhost:80}
/# curl -s -XPOST -H "Content-type: application/json" -H "Authorization: Key demo-key" ${ENDPOINT}/alert -d '
{
"resource": "host678:eth0",
"event": "HW:NIC:FAILED",
"group": "Hardware",
"severity": "major",
"environment": "Production",
"service": [
   "Network"
],
   "text": "Network interface eth0 is down.",
   "value": "error"
 }'
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

**Comment by BCWilsonDotCom** [comment]
I see the problem. All of the docs, including the api page (/api) and the create-alerts.sh script, point to the endpoints existing at the root level. However they actually exist under /api. Ex: localhost/api/alert instead of localhost/alert

This may be an actual alerta issue and not just something missing or changed in this docker implementation.

**Comment by satterly** [comment]
The API is [proxied](https://github.com/alerta/docker-alerta/blob/master/nginx.conf#L45) by nginx to `/api` in this Docker image so that it only needed to `EXPOSE` one TCP port. The `README` does mention that the API endpoint is at:
```
http://<docker>:<port>/api
```
However it sounds like this could be made more obvious so maybe some comments could be added to the `Dockerfile`.
