### ISSUE TITLE
403 http response when used in conjunction with nagios plugin

### ISSUE THREAD

**Issue by calerogers** [alerta/docker-alerta#10]
I get a 403 http response while using the docker alerta container and the nagios integration when I try to set an environment. It looks like I have to set an ALLOWED_ENVIRONMENT in alertad.conf? But there doesn't appear to be an environment variable to set that at docker run time.

**Comment by satterly** [comment]
You're right. Doesn't look like the reject plugin config options are supported.

**Comment by satterly** [comment]
Hi @calerogers I've just updated the Docker container image. Can you try it and see if your problem is fixed now? Thanks.

**Comment by calerogers** [comment]
That did the trick. Thanks!
