### ISSUE TITLE
Ack button disabled on some alerts.

### ISSUE THREAD

**Issue by PMDubuc** [alerta/docker-alerta#103]
We're using Alerta 6.0.1 and I've noticed that the Ack button doesn't work for alerts that were sent from Prometheus  Alertmanager even though the user has the admin role and scope and can execute all the other commands (Delete, Close, Open, Watch, Shelve). Sending similar alert with the alerta CLI produces and alert that can be acknowledged by the user.  I'm wondering how this can happen.  Was there a bug in this version, or if there is a problem with the way we've set up the admin user where it doesn't have permission to ack, but can do everything else.  We plan to upgrade to Alerta 6.6 but don't have the time right now.

**Comment by satterly** [comment]
I've no idea how or why this would happen. Here is a diff of everything that has changed since v6.0.1 ... 
https://github.com/alerta/angular-alerta-webui/compare/v6.0.1...master
I can't see anything obvious, so it could still be an issue now. I'd need to test.

**Comment by PMDubuc** [comment]
Thanks.  It does seem weird that all the other operations work but not the ACK.  Probably something related to our install.

**Comment by PMDubuc** [comment]
FYI, I found the problem.  The ALERTMANGER_URL wasn't configure in the alertad.conf file.  The Ack fails for messages from Prometheus Alertmanager because the attempt to silence the alert in Alertmanager fails.

**Comment by satterly** [comment]
Thanks for looping back. I'll make a note of trying to bubble up these sorts of errors in the web console.
