### ISSUE TITLE
API URL doesn't work after running Docker container

### ISSUE THREAD

**Issue by te4336** [alerta/docker-alerta#118]
When running the API server in the docker container the web UI works however when I got to access the API link I get the following...

{"code":500,"errors":["Traceback (most recent call last):\n  File \"/venv/lib/python3.6/site-packages/werkzeug/routing.py\", line 1538, in match\n    rv = rule.match(path, method)\n  File \"/venv/lib/python3.6/site-packages/werkzeug/routing.py\", line 776, in match\n    raise RequestSlash()\nwerkzeug.routing.RequestSlash\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/venv/lib/python3.6/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/venv/lib/python3.6/site-packages/flask/app.py\", line 1791, in dispatch_request\n    self.raise_routing_exception(req)\n  File \"/venv/lib/python3.6/site-packages/flask/app.py\", line 1774, in raise_routing_exception\n    raise request.routing_exception\n  File \"/venv/lib/python3.6/site-packages/flask/ctx.py\", line 336, in match_request\n    self.url_adapter.match(return_rule=True)\n  File \"/venv/lib/python3.6/site-packages/werkzeug/routing.py\", line 1542, in match\n    safe='/:|+') + '/', query_args))\nwerkzeug.routing.RequestRedirect: 301 Moved Permanently: None\n"],"message":"301 Moved Permanently: None","status":"error"}

Is there a way to fix this? I followed the directions for the docker container to the letter.

**Comment by satterly** [comment]
Does it work if you add a "/" to the end of the API URL? eg. instead of trying `http://example.com:8888/api` try `http://example.com:8888/api/` and see if you get a list of API resource endpoints and no errors?

**Comment by te4336** [comment]
adding the "/" worked. Was just weird as we didn't need that when it was running as a WSGI app natively on the server. Thanks for helping!

**Comment by satterly** [comment]
No problem. And yes, it is weird. I'm putting in a fix for it anyway.
