### ISSUE TITLE
housekeeping environment variable

### ISSUE THREAD

**Issue by Aschenbecher** [alerta/docker-alerta#119]
Is there a way to change the housekeeping time settings with environment variables or config files for alerta-docker? I just found the way over the Cli, but I need the settings persistent.

**Comment by satterly** [comment]
Did you try `HEARTBEAT_SEVERITY` - severity used to create alerts for stale heartbeats ?

**Comment by Aschenbecher** [comment]
I´m looking for a solution to increase the expire time for closed alerts, at the moment it is 2 hours I think.

**Comment by satterly** [comment]
You can only set the expire time for closed alerts as a URL parameter at present. This should probably be exposed as a server config setting and environment variable.

https://github.com/alerta/alerta/blob/master/alerta/management/views.py#L150-L151

```
        expired_threshold = int(request.args.get('expired', DEFAULT_EXPIRED_DELETE_HRS))
        info_threshold = int(request.args.get('info', DEFAULT_INFO_DELETE_HRS))
```

**Comment by satterly** [comment]
In the next release you will be able to configure these settings in the `alertad.conf` server config file like so...
```
# Housekeeping settings
DEFAULT_EXPIRED_DELETE_HRS = 2  # hours
DEFAULT_INFO_DELETE_HRS = 12  # hours
```

**Comment by Aschenbecher** [comment]
Good to know, thank you very much!
