### ISSUE TITLE
ERROR:flask.app:module 'alerta.build' has no attribute 'BUILD_NUMBER'

### ISSUE THREAD

**Issue by seasurfpete** [alerta/docker-alerta#120]
**Issue Summary**
latest docker build (6.8.1) is reporting no version info in the 'about page'
log file is reporting 

ERROR:flask.app:module 'alerta.build' has no attribute 'BUILD_NUMBER'
AttributeError: module 'alerta.build' has no attribute 'BUILD_NUMBER'

I will see if I can find the cause over the next couple of days. as a side note the client inside the container can't connect to the api. unsure if related.

**Environment**
- OS: linux
- API version: [ 6.8.1]
- Deployment: [eg. Docker, openshift]
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]

- Database: mongo
- Server config:
  Auth enabled? No
  
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**
click on about in webpage

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**
version displayed

**Screenshots**

**Additional context**

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by satterly** [comment]
Not sure why, but #108 broke a few things. Rather than spend a lot of time working out how and why (esp. when I didn't make the change) I have just [reverted it](3cfb14880921f64d306d131dc0eaaeb236aa2ae9) and all seems fine again now.
