### ISSUE TITLE
Automatic status update to closed not working any more

### ISSUE THREAD

**Issue by oiseger** [alerta/docker-alerta#121]
Hi, 

Not sure where to post my question, but I think I'm overlooking something.
I am using Prometheus Alertmanager (v 0.15.3) as alert source and noticed alerts are not being closed anymore.  I suspect this to be the case since a recent upgrade of Alerta from v 5.2.0 to 6.5.0 

Tried demo alerts from  https://docs.alerta.io/en/latest/gettingstarted/tutorial-4-alerts.html#step-3-automatic-status-changes
Severity is set to 'normal' but the auto-change of status to 'closed'  is not working.

Could this have something to do with housekeeping (which is disabled in my setup) ? 

Version: Alerta 6.5.0. with a Mongodb backend, running in Docker: alerta/alerta-web:6.5.0

**Comment by satterly** [comment]
Auto-closing cleared/normal alerts is not dependent on housekeeping -- only auto-closing of expired alerts. I'll see if I can reproduce.

**Comment by oiseger** [comment]
Ok, thanks, Good to know I can rule out housekeeping.
I'll try to create a fresh deploy to see if I can reproduce there

**Comment by oiseger** [comment]
Hi, 


I deployed a relatively clean 6.5.0 version (Ansible deployment, Alerta running in a Docker container)

```
docker exec -ti alerta-web-test alerta send -r user01 -e loginStatus -v loginOk -s warning -E Production -S Security -t 'user01 login success.'


> docker exec -ti alerta-web-test alerta query
ID        LAST RECEIVED        SEVERITY    STATUS      DUPL  CUSTOMER    ENVIRONMENT
--------  -------------------  ----------  --------  ------  ----------  -------------
e351e063  2019/03/25 13:28:11  warning     open           0              Production


> docker exec -ti alerta-web-test alerta send -r user01 -e loginStatus -v loginOk -s normal -E Production -S Security -t 'user01 login success.'

> docker exec -ti alerta-web-test alerta query
ID        LAST RECEIVED        SEVERITY    STATUS      DUPL  CUSTOMER    ENVIRONMENT
--------  -------------------  ----------  --------  ------  ----------  -------------
e351e063  2019/03/25 13:29:21  normal      open           0              Production    
```
So not working as expected (which is to close the alert)


After that I switched to version 6.8.2, and seems to work now.  
So for me the issue is no longer an issue, I'll take the liberty of closing this issue,

**Comment by oiseger** [comment]
I'm a little confused though, https://hub.docker.com/r/alerta/alerta-web/tags  has latest version (tag) 6.8.2  whereas git latest release is v6.5.0 (https://github.com/alerta/docker-alerta/releases)
