### ISSUE TITLE
404 Not found after refresh the page

### ISSUE THREAD

**Issue by wmariuss** [alerta/docker-alerta#126]
**Issue Summary**
When i try to refresh the page, i got 404 Not found. I did not try to run just the UI without nginx.

E.g. <url>/alerts#status:open,ack;dateRange:,;sb:default;sd:1

**Environment**
docker image version alerta-web:7.0.1

- Database: [eg. MongoDB, Postgres]

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? No

**To Reproduce**
1. Type alerta url in the browser
2. Refresh the page

[Screenshot](https://www.dropbox.com/s/hs2c3hwwa2d2qge/Screenshot%202019-04-24%2017.57.11.png?dl=0)

**Comment by wmariuss** [comment]
P.S. I was not sure if this related to nginx or just Web UI

**Comment by satterly** [comment]
It's an nginx thing. I'm aware of the issue and working on a fix. /cc @jurgenhaas
