### ISSUE TITLE
Requested scope 'read' not in existing scopes

### ISSUE THREAD

**Issue by satterly** [alerta/docker-alerta#127]
**Issue Summary**
On CentOS 7, with docker install (from two days ago), when I try to create a user, the page slides up: "Requested scope 'read' not in existing scopes: (403). And does not create the user. I created a user because when trying to create an API key the page slides up: "An API key must be associated with a 'user'. Retry with user credentials. (400).

**Environment**
- OS: [eg. Linux, Mac, Windows]
- API version: [eg. 6.8.1]
- Deployment: [eg. Docker, Heroku, AWS, GCloud, self-hosted]
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]

- Database: [eg. MongoDB, Postgres]

- Server config:
  Auth enabled? Yes/No
  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
  Customer views? Yes/No
  (or provide the `/config` endpoint output)

- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**
Docker Install:
$ docker run --name alerta-db -d mongo
$ export DATABASE_URL=mongodb://db:27017/monitoring
$ docker run --name alerta-web -e DATABASE_URL=$DATABASE_URL --link alerta-db:db \
-d -p 8080:8080 alerta/alerta-web

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**

**Screenshots**
docker logs and screenshots here: https://docs.google.com/document/d/11712QDtyydU-566FEpeYEmr2y6Hg-CB8GGBeWxnJJIQ/edit?usp=sharing

**Additional context**
(none)

/cc @danfoxley

**Comment by satterly** [comment]
I would guess you haven't enabled authentication, so when you go to create a user with default scopes of `read` and `write` it gives an error saying you don't have `read` scope because you aren't logged in.

You only wanted to create a user because an API key needs to be associated with a user but if you haven't enabled authentication then API keys are not required.

Did you know what authentication is disabled by default? If so, do you want to enable it?

**Comment by danfoxley** [comment]
I figured this may be user error with installing the Docker instance, I used https://github.com/alerta/docker-alerta#how-to-use-this-image. and had a feeling it didn't have all the required options.

Would using the config spelled out in the Docker compose (but I won't use Docker compose) be a better installation to start with, any suggestions for a full featured config of Alerta?

**Comment by satterly** [comment]
Yes, starting with one of the configs from a docker compose file would be a good option. Most assume auth should be enabled and default to "basic". There are several examples [here](https://github.com/alerta/docker-alerta/tree/master/examples) and I'm adding more right now #129.

**Comment by danfoxley** [comment]
Per this:
https://github.com/alerta/docker-alerta#authentication
"To make it easy to get going with Alerta on docker quickly, the default image will use Basic Auth for user logins and login will be optional."

Should basic auth have worked and I would have had been able to create user/API Key?

**Comment by satterly** [comment]
Yes, if you had logged in -- but you hadn't. I'll log an issue to make it possible to log in even though auth isn't required. (this is a regression from a previous version where this used to be possible).

**Comment by satterly** [comment]
Fixed by alerta/alerta-webui#174
