### ISSUE TITLE
Not working with custom BASE_URL

### ISSUE THREAD

**Issue by proffust** [alerta/docker-alerta#138]
**Issue Summary**
When I set custom BASE_URL web not working, but api working

**Environment**
- OS: Linux,
- API version: 7.2.7
- Deployment: Docker

- Database: MongoDB

- Server config:
  Auth enabled? No
  Customer views? No

- web UI version: 7.2.7
- CLI version: 7.2.7

**To Reproduce**
1. Go to docker_compose.yml
2. Replace BASE_URL to /alerta/api
3. Run container
`2019/05/23 16:55:32 [error] 35#35: *36 rewrite or internal redirection cycle while internally redirecting to "/alerta/index.html", client: 172.16.5.254, server: , request: "GET /alerta/ HTTP/1.1", host: "172.30.0.86:8080"
2019-05-23 16:55:32,653 DEBG 'nginx' stdout output:
ip=\- [\23/May/2019:16:55:32 +0000] "\GET /alerta/ HTTP/1.1" \500 \595 "\-" "\Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.83"
/web | /alerta/index.html | > GET /alerta/ HTTP/1.1
`

**Expected behavior**
Alerta starting with custom BASE_URL

**Screenshots**
![image](https://user-images.githubusercontent.com/33157540/58271520-e610c000-7d94-11e9-8d6c-10568d5846e1.png)
![image](https://user-images.githubusercontent.com/33157540/58271715-5d465400-7d95-11e9-98d9-9970471a4639.png)

**Comment by satterly** [comment]
Try it now and let me know if it's working again.

**Comment by satterly** [comment]
@proffust Is this working for you now, then?
