### ISSUE TITLE
Links for fonts and audio file broken if behind proxy

### ISSUE THREAD

**Issue by satterly** [alerta/docker-alerta#141]
**Issue Summary**
If alerta web UI is served behind another proxy links to fonts and the default audio file are broken.

**Environment**
- OS: Linux
- API version: 7.x
- Deployment: Docker + any other deployment to a subpath
- For self-hosted, WSGI environment: nginx

- Database: any

- Server config:
  Auth enabled? Yes/No
  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
  Customer views? Yes/No
  (or provide the `/config` endpoint output)

- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**
1. Run alerta-web docker behind nginx proxy
2. Go to home page and observe broken fonts and no audio

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/33157540/58324935-fa09ff80-7e30-11e9-8bde-3e8cc22f477e.png)

**Additional context**
See #140 

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

/cc @proffust

**Comment by satterly** [comment]
This works...
```
                location /alerta {
                        # proxy_set_header        Host $host;
                        # proxy_set_header        X-Real-IP $remote_addr;
                        # proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                        # proxy_set_header        X-Forwarded-Proto $scheme;
                        proxy_pass          http://127.0.0.1:8080;
                        # proxy_read_timeout  90;
                }
                location /audio {
                        proxy_pass          http://127.0.0.1:8080/audio;
                }
                location /fonts {
                        proxy_pass          http://127.0.0.1:8080/fonts;
                }
```

**Comment by proffust** [comment]
it`s work, but locations /audio and /fonts may already be busy

**Comment by satterly** [comment]
True. I should have added that I didn't think this was a long-term solution, only that it works for now.

**Comment by satterly** [comment]
This should work now with the latest docker image...
```
                location /alerta {
                        # proxy_set_header        Host $host;
                        # proxy_set_header        X-Real-IP $remote_addr;
                        # proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                        # proxy_set_header        X-Forwarded-Proto $scheme;
                        proxy_pass          http://127.0.0.1:8080;
                        # proxy_read_timeout  90;
                }
```
Let me know if this solves your issue.

**Comment by proffust** [comment]
yes, it`s works
