### ISSUE TITLE
Alerta Docker with No IPv6

### ISSUE THREAD

**Issue by BenB196** [alerta/docker-alerta#146]
**Issue Summary**
Trying to start the Alerta Docker container on a system which does not support IPv6, causes nginx to fail to start, thus making Alerta unusable.

**Environment**
- OS: Linux (Photon OS)
- API version: latest
- Deployment: Docker (Docker Compose)
- For self-hosted, WSGI environment: N/A

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? No

- web UI version: latest
- CLI version: latest

**To Reproduce**
1. Run the Alerta docker container on a system which does not support IPv6
2. Look at container logs; Alerta will be in an infinite loop saying nginx failed to start
3. The Alerta container will stay active, so much check logs for the error.

**Expected behavior**
I would expect that the Alerta container should be able to work correctly whether IPv6 is supported or not.

**Additional context**
Removing the following line from nginx.conf fixes the issue, I don't know what the optimal way would be to go about solving it in a more permanent way.

`                listen [::]:8080 default_server;`

URL of line: https://github.com/alerta/docker-alerta/blob/470a447a3573f8b505d53a0109fec3cd8c2e4658/nginx.conf#L34

**Comment by satterly** [comment]
I have reversed the assumption here because apparently [GCP still does not support IPv6 at instance level](https://googlecloudplatform.uservoice.com/forums/302595-compute-engine/suggestions/8518246-support-ipv6) (yes, it is 2019!!). So for now the docker image supports IPv4 only and IPv6 support will require custom image build.
