### ISSUE TITLE
All auth providers should work in supported image

### ISSUE THREAD

**Issue by satterly** [alerta/docker-alerta#149]
**Issue Summary**
Basic LDAP and SAML2 require additional python libraries which aren't installed by default. They should be so that it isn't necessary to build a custom image to use any of the available auth providers.

**Environment**
- OS: [eg. Linux, Mac, Windows]
- API version: [eg. 6.8.1]
- Deployment: [eg. Docker, Heroku, AWS, GCloud, self-hosted]
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]

- Database: [eg. MongoDB, Postgres]

- Server config:
  Auth enabled? Yes/No
  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
  Customer views? Yes/No
  (or provide the `/config` endpoint output)

- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**
2. Click on '....' or Run '...'
4. See error (include command output)

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**

**Screenshots**

**Additional context**
See #142

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by jackdown** [comment]
Is there a problem to add least add the LDAP dependencies to the current standard build?
 Like you do in https://github.com/alerta/docker-alerta/blob/master/examples/ldap/Dockerfile .

**Comment by jackdown** [comment]
Is it possible to add the python-ldap to the requierments.txt to use LDAP at default?

**Comment by satterly** [comment]
Yes, it is now. It was blocked until a config option was added here ... https://github.com/alerta/alerta/blob/master/alerta/auth/__init__.py#L20

**Comment by jackdown** [comment]
Thanks for this fast response :)

**Comment by satterly** [comment]
Pysaml2 added in #168
