### ISSUE TITLE
Update Dockerfile to use Debian buster for mongodb clients

### ISSUE THREAD

**Issue by satterly** [alerta/docker-alerta#153]
Debian buster was released on 6 July 2019 but no longer supports the Debian maintained `mongodb-clients` package so the Dockerfile will need to be updated to use official mongo packages from now on. However there aren't official packages for buster as far as I can tell... 

See http://repo.mongodb.org/apt/debian/dists/
```

Index of dists
--
 
Parent Directory
jessie
stretch
wheezy
 
repo.mongodb.org
```

See https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/

Note: The Dockerfile is currently pinned to use Debian stretch for the time being. See ab67fd16cc0280d0bbe88df2de23e5e153fbd233

**Comment by jackdown** [comment]
There is now a offical repo but I'm unsure about the right package. Is it mongodb-org-shell?
