### ISSUE TITLE
Include pysaml2

### ISSUE THREAD

**Issue by zenman94** [alerta/docker-alerta#167]
Can you include pysaml2 in docker image please ? 

Thanks

**Comment by satterly** [comment]
Yes this should have been done as #142 but was closed because v7 didn't support SAML logins.

**Comment by zenman94** [comment]
Ok sorry I don't see that.
I have to retry with ldap so.

**Comment by satterly** [comment]
Done. Run `docker pull alerta/alerta-web:f3888ea`
