### ISSUE TITLE
Web UI only refreshes when browser cache disabled

### ISSUE THREAD

**Issue by jurgenhaas** [alerta/docker-alerta#171]
**Issue Summary**

Installed Alerta on a new host (full config is in #170) with Docker image alerta/alerta-web and everything seems to be working just fine. Except that the alerts in the browser are not refreshing unless I'm disabling browser cache.

The vhost.conf for Apache 2.4 looks like this:

```
<VirtualHost *:443>
  Options +FollowSymLinks
  RewriteEngine on
  RequestHeader unset Proxy early

  ServerAdmin webmaster@example.com
  ServerName  alerta.lakedrops.com

  Header always add Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"

  RequestHeader set Host alerta.lakedrops.com
  RequestHeader set X_FORWARDED_PROTO 'https'
  RequestHeader set X-Forwarded-Ssl on
  RequestHeader set X-Forwarded-For alerta.lakedrops.com

  DocumentRoot /var/www/html

  <Proxy *>
    <RequireAll>
      Require all granted
    </RequireAll>
  </Proxy>

  ProxyPass / http://localhost:8091/
  ProxyPassReverse / https://alerta.lakedrops.com/
  ProxyPreserveHost On

  ErrorLog ${APACHE_LOG_DIR}/alerta.lakedrops.com-error.log
  LogLevel warn
  LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
  SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
  CustomLog ${APACHE_LOG_DIR}/alerta.lakedrops.com-access.log combined env=!forwarded
  CustomLog ${APACHE_LOG_DIR}/alerta.lakedrops.com-access.log proxy env=forwarded

  <IfModule mod_expires.c>
    ExpiresActive On
    ExpiresDefault A14400
    ExpiresByType text/html A900
  </IfModule>

  SetEnvIf X-Forwarded-Proto https HTTPS=on

  BrowserMatch "MSIE [2-6]" \
    nokeepalive ssl-unclean-shutdown \
    downgrade-1.0 force-response-1.0
  # MSIE 7 and newer should be able to use keepalive
  BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

  SSLEngine on
  Include /etc/letsencrypt/options-ssl-apache.conf
  SSLCertificateFile /etc/letsencrypt/live/alerta.lakedrops.com/cert.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/alerta.lakedrops.com/privkey.pem
  SSLCertificateChainFile /etc/letsencrypt/live/alerta.lakedrops.com/chain.pem
</VirtualHost>
```

**Comment by satterly** [comment]
Try with the latest docker image version 7.4.5. I have simplified the container config so even if it still doesn't work it should be easier to debug.

**Comment by jurgenhaas** [comment]
Looks like the new version doesn't make any difference but I found a way to disable caching on the apache proxy level with additional settings:

```
FileETag None
Header unset ETag
Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
Header set Pragma "no-cache"
Header set Expires "Wed, 11 Jan 1984 05:00:00 GMT"
```

That way, all my browser UIs are properly updating themselves as expected. Maybe that's a useful addition to the documentation.

**Comment by satterly** [comment]
Would adding any headers to the Alerta nginx help?

**Comment by jurgenhaas** [comment]
That's a good question, TBH I don't know Nginx well enough to be able to answer that. But I'd be happy to test if you could provide an image with respective settings.

**Comment by satterly** [comment]
I just created an example docker setup using apache as a reverse proxy and the web UI auto-updates as expected. Not sure why yours doesn't. See #181

**Comment by satterly** [comment]
Closing this for now. Can reopen if you provide a docker config that reliably reproduces the issue.

**Comment by jurgenhaas** [comment]
This looks great. I wonder if the key thing is the `USE_PROXYFIX = True` setting in alertad.conf ?

It's now working for me too.

**Comment by jurgenhaas** [comment]
Thanks a lot @satterly, I've played with it a bit more and everything is looking great now. For our own use I've created an [Ansible role](https://gitlab.lakedrops.com/ansible-roles/alerta) for this which initially installs and later automatically updates an existing instance - just in case you wanted to share that with others.

**Comment by satterly** [comment]
That's good news. And I will link to the Ansible role work from the docs. Thanks!
