### ISSUE TITLE
Keycloak integration with Docker

### ISSUE THREAD

**Issue by burakksglu** [alerta/docker-alerta#172]
**Issue Summary**
There is a login-logout loop behaviour with keycloak as authentication provider. It happens if browser cache is disabled. Otherwise it shows "\logout " page but it doesn't actually redirect to logout page.

**Environment**
- OS: Linux
- API version: 7.4.4
- Deployment: Docker

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Keycloak
  Customer views? No 

- web UI version: 7.4.1
- CLI version: 7.4.4

**To Reproduce**
1. Open the developer console on browser and disable caching.
2. Login and then logout from Alerta via Keycloak 
3. Wait for logout
4. Ypu will see that it automatically logins after logging out.

**Expected behavior**
Logout button should redirect to the "OIDC_LOGOUT_URL" path given from environment.

**Screenshots**
Cache disabled:
![image](https://user-images.githubusercontent.com/49399656/78261275-b4fe3180-7507-11ea-8887-ec21a6fb8a6d.png)

Cache enabled:
![image](https://user-images.githubusercontent.com/49399656/78261323-c47d7a80-7507-11ea-9dfc-a415ba0443d6.png)

```              
DEBUG = "True"
DATABASE_URL = "postgres://user:pass@alerta-postgres:5432/alerta"
ADMIN_USERS = "admin"
ADMIN_PASSWORD = "password"
ADMIN_KEY = "ZvyhEvn5ujkhwuCXTA_Z6VbqzBwFfMNVOKp-27fh"
SIGNUP_ENABLED = "False"
AUTH_REQUIRED = "True"
AUTH_PROVIDER = "keycloak"
KEYCLOAK_URL = "http://<keycloak-ip>:8040"
KEYCLOAK_REALM = "test-realm"
OAUTH2_CLIENT_ID = "alerta-ui"
OAUTH2_CLIENT_SECRET = "e2c5bcf4-e1d3-4832-aeba-50cbc2b81a69"
ALLOWED_KEYCLOAK_ROLES = "admin,guest,user"
OIDC_LOGOUT_URL = "http://<keycloak-ip>:8040/auth/realms/test-realm/protocol/openid-connect/logout"
```
Note: Syntax might look different on the environment variables since I use terraform to deploy docker. I can confirm they are valid tho. I've tested with docker-compose also.

**Comment by decentral1se** [comment]
<3 <3 <3

**Comment by satterly** [comment]
The OIDC_LOGOUT_URL is dynamically determined using the OpenID connect discovery endpoint. Why are you setting it? And what is it being set to when it is actually called? (I can't tell from the screenshots as they are too small).

**Comment by burakksglu** [comment]
We added logout url because user wasn't actually logging out after clicking logout button on the Alerta. We started without the "adding OIDC_LOGOUT_URL" first but then this setting was suggested.

**Comment by burakksglu** [comment]
![image](https://user-images.githubusercontent.com/49399656/78891419-33ab1f80-7a70-11ea-9098-c60c26ee1abd.png)

1920x1080 screenshot of network page for you to check.

**Comment by satterly** [comment]
What's the response body for `/auth/logout` ?

**Comment by burakksglu** [comment]
![image](https://user-images.githubusercontent.com/49399656/78892946-fac07a00-7a72-11ea-864e-c3fcb9ff3fd6.png)

Payload for extra information:

![image](https://user-images.githubusercontent.com/49399656/78892978-0875ff80-7a73-11ea-9873-053a0542be71.png)

**Comment by satterly** [comment]
I don't understand. What was there before you typed "my-realm"?

And what happens if you manually click on that link? Do you get logged out of Keycloak? Or just Alerta?

**Comment by burakksglu** [comment]
I've changed the realm name because of security reasons but it's the correct address. It returns 200 OK:
![image](https://user-images.githubusercontent.com/49399656/78895225-1d549200-7a77-11ea-9cfc-8b1d0a491d29.png)


The problem is I think Alerta redirects and prompts login right after logout. It doesn't redirect to the logout page after clicking the logout button. It goes back to the OIDC logout url path, waits for 1-2 seconds then logs me in without asking anything. While doing that it gave Missing API Key or Bearer Token error.

If you can check the below screenshot there's also 401 error which says on the first and second error after logout request:
```
{
  "code": 401, 
  "errors": null, 
  "message": "Missing authorization API Key or Bearer Token", 
  "requestId": null, 
  "status": "error"
} 
```


> ![image](https://user-images.githubusercontent.com/49399656/78891419-33ab1f80-7a70-11ea-9098-c60c26ee1abd.png)
> 
> 1920x1080 screenshot of network page for you to check.

**Comment by satterly** [comment]
It's because there were two 401 responses received after you logged out. Alerta is configured to redirect to the `/login` page if that happens. And if you're using something like Keycloak it will automatically re-authenticate. It seems that the logout redirect doesn't actually log you out of your Keycloak session if Keycloak doesn't prompt you again for your credentials.

So I'll ask again ... what happens if you manually click on that link? Do you get logged out of Keycloak? Or just Alerta? Or neither? Do you still have keycloak session cookies or the Alerta bearer token in your browser local storage (`auth.token`)?

<img width="1019" alt="Screenshot 2020-04-09 at 16 01 57" src="https://user-images.githubusercontent.com/615057/78903513-8807cc80-7a7b-11ea-99a3-7eafa168d816.png">

**Comment by burakksglu** [comment]
OK I will try to answer again one by one.

Yes, i clicked the link and it did logged me out on the realm:
![image](https://user-images.githubusercontent.com/49399656/78904353-0e74dc00-7a85-11ea-8e15-f1353521abdd.png)

Also I've another application uses the same end session endpoint it did also logout after I clicked the link.

This the local storage, cookie and session storage in order:

![image](https://user-images.githubusercontent.com/49399656/78904746-aa9ee300-7a85-11ea-9854-4330490bcb14.png)

![image](https://user-images.githubusercontent.com/49399656/78904900-e8037080-7a85-11ea-9ace-04c69cb13803.png)

Session storage is empty:
![image](https://user-images.githubusercontent.com/49399656/78904935-f487c900-7a85-11ea-9bc3-f908ba6a70ed.png)

Hope this will help.
Thank you for your time and help.

By the way please stay safe & healty Nick!
Best,
Burak

**Comment by burakksglu** [comment]
I believe there was a typo in mention, so i will be looking forward to a possible solution.

Also we might have the same problem with the alerta/alerta#1181

**Comment by burakksglu** [comment]
I believe there was a typo in mention, so i will be looking forward to a possible solution.

Also we might have the same problem with the alerta/alerta#1165

**Comment by satterly** [comment]
Are you building your own docker container? Have you deployed it behind a reverse proxy? On a subpath?

**Comment by burakksglu** [comment]
I am not building my own docker and using localhost, so no proxies. I'm pulling image from alerta/alerta-web:7.4.5 and then passing db and auth provider parameters as environment variable. Then I expose port 8080. That's all the configuration I have on the container.

**Comment by burakksglu** [comment]
This is all actually.

```
image = "alerta/alerta-web:7.4.5"

               DEBUG = "True"
               DATABASE_URL = <dbpath>
               ADMIN_USERS = "${var.admin_user}"
               ADMIN_PASSWORD = "${var.admin_pass}"
               ADMIN_KEY = "ZvyhEvn5ujkhwuCXTA_Z6VbqzBwFfMNVOKp-27fh"
               SIGNUP_ENABLED = "False"
               AUTH_REQUIRED = "True"
               AUTH_PROVIDER = "keycloak"
               KEYCLOAK_URL = "http://<keycloak-ip>:8040"
               KEYCLOAK_REALM = <myrealm>
               OAUTH2_CLIENT_ID = "alerta-ui"
               OAUTH2_CLIENT_SECRET = "e2c5bcf4-e1d3-4832-aeba-50cbc2b81a69"
               ALLOWED_KEYCLOAK_ROLES = "admin,guest,user"
```

**Comment by satterly** [comment]
This should be fixed in the next release of web UI.

**Comment by burakksglu** [comment]
> This should be fixed in the next release of web UI.

Great news. I will try to test when it's available Nick. Nice effort, thanks!
