### ISSUE TITLE
Add configurable port instead of hardcoding 8080

### ISSUE THREAD

**Issue by decentral1se** [alerta/docker-alerta#176]
**Is your feature request related to a problem? Please describe.**
I am using dokku.viewdocs.io/dokku to deploy (open source Heroku) (using https://github.com/alerta/docker-alerta) which uses the proxy ports plugin (see https://github.com/dokku/dokku/blob/master/docs/networking/port-management.md) by default which reads the `EXPOSE` definition of the Dockerfile and maps that port to Nginx proxying. Since 8080 is such a common port, this conflicts with other containers. Dokku doesn't easily allow to do the usual `-p 9090:8080` magic where you re-map the port. Hence, I need an application level port configuration.

**Describe the solution you'd like**
Have a configuration option to choose a new port so that I can override the Dockerfile and specify that new port with an `EXPOSE ....` definition.

**Describe alternatives you've considered**
Checked the docs... saw https://github.com/alerta/alerta/issues/178...

**Additional context**
Unsure.

**Comment by decentral1se** [comment]
Your opinions on Dokku are not cause to close this ticket. Whatever Dokku does is irrelevant, this ticket is about a lack of configurable port in Alerta. This ticket should be re-opened. Furthermore, adding a `EXPOSE` statement to a Dockerfile with a different port will not magically make Alerta change the port that it exposes itself on therefore making my new port useless.

**Comment by satterly** [comment]
The documentation you refer to recommends the same fix that I suggested above ...
> If you would like to change the exposed port, you should do so within your Dockerfile.

https://github.com/dokku/dokku/blob/master/docs/networking/port-management.md#dockerfile

So create your own Dockerfile with a different `EXPOSE` port and modify the `nginx.conf` file to match... https://github.com/alerta/docker-alerta/blob/master/nginx.conf#L33

**Comment by decentral1se** [comment]
Yes, I have also found this option in Dokku since I first posted. However, that is again irrelevant. This is about a configurable port in the alerta software. Why has this been marked wont-fix? Because there are other work arounds? It would be easier for some to pass the port in via an env var... even if you don't intend to do it yourself someone else could make this configurable?

**Comment by satterly** [comment]
Rereading the port management page again I clearly states that host->container port mapping is now supported ...
>You can now configure host -> container port mappings with the proxy:ports-* commands. This mapping is currently supported by the built-in nginx-vhosts plugin.
