### ISSUE TITLE
[docs] Things to do

### ISSUE THREAD

**Issue by satterly** [alerta/docker-alerta#19]
- [x] pre-install plugins as a layer
 - [x] Config file volumes
 - [x] What is alerta
 - [x] Environment variable info
 - [x] not linking db container
 - [x] Test “how to use this image” against entry point image
 - [x] Use labels?
 - [x] Alpine linux version?
 - [x] write tutorial for newbies

**Comment by RafaelSnor** [comment]
Add a tutorial for newbies pls

**Comment by satterly** [comment]
See https://docs.alerta.io/en/latest/gettingstarted/tutorial-10-docker.html#tutorial-10
