### ISSUE TITLE
alerta 8.0.3 on docker

### ISSUE THREAD

**Issue by w-HA** [alerta/docker-alerta#228]
Hi,

it seems alerta 8.0.3 is not available on docker .

Thansk
Benoit

**Comment by KlavsKlavsen** [comment]
and also helm-chart is still pointing to 7.5.1.. I updated my own to use 8.0.3 and it works like a charm (and with  many improvements I needed :)

**Comment by satterly** [comment]
Fixed c77f7f490089ae185637656487614becc1215696
