### ISSUE TITLE
slow boot up of alerta pods

### ISSUE THREAD

**Issue by jsfrerot** [alerta/docker-alerta#230]
**Issue Summary**
when creating/updating pods for alerta it take about 5 minutes to become READY

**Environment**
- OS: Kubernetes on linux
- API version: 8.0.2
- Deployment: Docker

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? Yes

- web UI version: 8.0.0

**To Reproduce**
1. helm install alerta --namespace alerta-jsfrerot ./
2. wait for pods to come online

**Expected behavior**
I'd like the pod to become READY much more faster.

**Additional context**
```
pod/alerta-7dc5bf546b-s4sq9   0/1     Running   0          4m8s
...
pod/alerta-7dc5bf546b-s4sq9   1/1     Running       0          5m9s
```
https://gist.github.com/jsfrerot/3e3b1f090be46535448fc5b67d706fc3

**Comment by KlavsKlavsen** [comment]
I see the same behavior

**Comment by satterly** [comment]
Any idea why?

**Comment by KlavsKlavsen** [comment]
Not yet - haven't looked into it.. It seems it talks to supervisor for "ready" tests - and it goes through a lot of steps or something - before it declares it ready.. Haven't dug into it.

**Comment by KlavsKlavsen** [comment]
I just looked. Previously the chart had an Initialdelay of 300 seconds for the readiness probe - which caused it. I also adjusted my liveness probe delay down to 10 seconds - but I don't thats actually necessary to solve this.
So its been resolved : https://github.com/alerta/docker-alerta/blob/master/contrib/kubernetes/helm/alerta/templates/deployment.yaml#L68

**Comment by satterly** [comment]
Great. Thanks for confirming. 👍
