### ISSUE TITLE
Cannot configure LDAP authN with docker-compose

### ISSUE THREAD

**Issue by xologram** [alerta/docker-alerta#231]
Hello, I am trying to set up alerta with docker-compose and LDAP authentication and I am consistently getting 403 unauthorized domain message. Does anyone know where can I set authorized domain for LDAP? I've set LDAP_DOMAINS* env variables in docker-compose file and no luck. I've tried:

    environment:
      - DEBUG=1  
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - AUTH_PROVIDER=ldap
      - LDAP_URL=ldaps://ldap.home.lan:636
      - "LDAP_DOMAINS={'home.lan': 'uid=%s,ou=users,dc=home,dc=lan'}"
      - "LDAP_DOMAINS_BASEDN={'home.lan': 'dc=home,dc=lan'}"
      - "LDAP_DOMAINS_GROUP={'home.lan': '(&(member={uid})(objectClass=groupOfUniqueNames))'}"
      - LDAP_ALLOW_SELF_SIGNED_CERT=True
      - ALLOWED_EMAIL_DOMAINS=home.lan
      - ADMIN_USERS=user@home.lan
      - PLUGINS=reject,blackout,normalise,enhance

what am I missing here?

**Comment by jsfrerot** [comment]
Are you using the email when you login to alterta webUI ?
user@home.lan ?

**Comment by xologram** [comment]
@jsfrerot yes and I get 403 unauthorized domain message. if I try without @home.lan I get message that full email is required. Also in the alerta-web container I see those LDAP_DOMAINS_* env variables are loaded when I look at `env` but logs don't say anything regarding this 403 message.

**Comment by satterly** [comment]
Not all server config variables are supported as environment variables. And none of them are `LDAP*` variables. Use an `alertad.conf` file like this example https://github.com/alerta/docker-alerta/blob/master/examples/ldap/docker-compose.yml#L7

**Comment by satterly** [comment]
Full list of environment variables supported by the Alerta docker container can be found on the Docker hub website https://hub.docker.com/repository/docker/alerta/alerta-web
