### ISSUE TITLE
audit logs not getting to console or file ?

### ISSUE THREAD

**Issue by KlavsKlavsen** [alerta/docker-alerta#236]
Running Alerta 8.0.2 on Kubernetes using this Helm chart.

When I set this:
```
AUDIT_TRAIL = ['admin', 'write', 'auth']
AUDIT_LOG = True  
AUDIT_LOG_REDACT = True
AUDIT_LOG_JSON = False
```
I don't see any audit logs in console output (pulling logs with kubectl).

somehow the setup of alerta inside docker is not getting all logs to stdout/stder ?

**Comment by satterly** [comment]
Could be a "blinker" issue. If the python package isn't installed it silently fails, I just learned.

**Comment by satterly** [comment]
Docker audit logs should be fixed if you can confirm. Thanks.
