### ISSUE TITLE
Offer Mongo option for Helm chart

### ISSUE THREAD

**Issue by te4336** [alerta/docker-alerta#246]
Currently the only option available for a datastore when using the Helm chart appears to be PostgreSQL. Would it be possible to have an option for Mongo as well? Would be great to have an option for both and let the end user decide which flavor of datastore they want to deploy.

**Comment by satterly** [comment]
Helm is not something I use or directly support so I'd be looking for help from the community to get this added.

**Comment by te4336** [comment]
Closing issue
