### ISSUE TITLE
Old postgresql dependency in helm chart

### ISSUE THREAD

**Issue by KlavsKlavsen** [alerta/docker-alerta#257]
The helm chart depends on postgresql 8.9.* - and it really should not.
I tested it with 9.1.x - and it worked just fine.. and should work with any version that alerta-api works with.
IMHO the requirement should be changed to the latest of the latest major version alerta-api supports ?

**Comment by te4336** [comment]
If anyone that has an opportunity and would add MongoDB support in to the Helm chart that would be awesome Issue #246

**Comment by satterly** [comment]
Yes, it should be at least Postgres 9.5 but 10 would be better as 9.6 is EOL in November 2021.
