### ISSUE TITLE
Alerta 8.1.0 not working behind reverse proxy

### ISSUE THREAD

**Issue by proffust** [alerta/docker-alerta#260]
**Issue Summary**

**Environment**
- OS: linux
- API version: 8.1.0
- Deployment: Docker

- Database: Mongo

- Server config:
  Auth enabled? No
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: 8.1.0
- CLI version: 8.1.0

**To Reproduce**
1. Run alerta-web 8.1.0 with settings
      - DEBUG=False
      - DATABASE_URL=mongodb://alerta-db:27017/monitoring
      - AUTH_REQUIRED=False
      - AUTH_PROVIDER=basic
      - ADMIN_USERS=
      - BASE_URL=/alerta/api
      - PLUGINS=slack,reject,heartbeat,blackout
alertad.conf:
SECRET_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx'
ALLOWED_ENVIRONMENTS = ['Production', 'Development', 'Testing']
SLACK_CHANNEL_ENV_MAP = { 'Production' : '#alert-prod', 'Testing' : '#alert-testing' }
2. reverse proxyt settings
    location /alerta/ {
        proxy_pass http://alerta-web:8080/;
    }
3. http://alerta-url/alerta/api work fine
4. http://alerta-url/alerta a see this
![image](https://user-images.githubusercontent.com/33157540/99401796-a67b5380-28f9-11eb-9808-ac85242bf9aa.png)
![image](https://user-images.githubusercontent.com/33157540/99401995-e80bfe80-28f9-11eb-89c8-213d794006c4.png)

in logs 
```
2020-11-17 14:17:57,448 DEBG 'nginx' stdout output:
ip=\- [\17/Nov/2020:14:17:57 +0000] "\GET /alerts/ HTTP/1.0" \304 \0 "\-" "\Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
/web | /index.html | > GET /alerts/ HTTP/1.0

```

For web app issues, include any web browser JavaScript console errors.
![image](https://user-images.githubusercontent.com/33157540/99401867-bc891400-28f9-11eb-897b-fb7534ecbfc0.png)

**Expected behavior**
working alerta-web with same settings. alerta-web 7.2.10 work fine

**Comment by satterly** [comment]
If you want to run Alerta on a subpath using Docker you can not use this image. You need to build your own. See #175

**Comment by proffust** [comment]
> If you want to run Alerta on a subpath using Docker you can not use this image. You need to build your own. See #175

hello. can you show an example of how to rebuild the image?

**Comment by satterly** [comment]
There are several in the `examples` directory. Here's the "nginx" one https://github.com/alerta/docker-alerta/blob/master/examples/nginx/README.md
