### ISSUE TITLE
ADMIN_USERS not working for more than 1 user

### ISSUE THREAD

**Issue by KlavsKlavsen** [alerta/docker-alerta#270]
**Issue Summary**
Using the chart, which ends up setting: ADMIN_USERS=user1, user2
ONLY username1 is actually an admin when I then LOGIN - the rest just get read privs.
The chart setting name is: alertaAdminUsers (and is an array that is then joined to form ADMIN_USERS env variable).

Output snippet from first startup in k8s with blank database:
```
 # Create admin users.
 Usage: alertad user [OPTIONS]
 Error: Not required for ldap admin users
 # Create admin API keys.
 JDUMqwa4b9ngy9hoS1FXSexyA1qRwM2s3qiwy-P- user1@example.org
 UR3_JhkT9VzeVmVtcwVKyoM8ypDaP0zn3V_NB_Hu  user2@example.org
 s5ay3K8spWGI2X_EC0oEQkZiaDV4rQjC_r_EBOCv  user3@example.org
 IUJhkF3SEVOKZkatvAROFKySEIyyT97NuI-g7stK  user4@example.org
 jMNyDzfSZBwCw3g-57c27Rz6IWdAHty9c_wOrpjP  user5@example.org
 -QLF4Uu4JCzEnAnYwz7kQ335AJR9BogSsVmyq3Nh  user6@example.org
 OICK69bJlZqwZy0WCF2W71TSBNrtOiZ1Q9ljYrIo  user7@example.org
 # Create client configuration file.
..
```

**Environment**
- OS: Linux
- API version: 8.1.0
- Deployment:Docker - Kubernetes
- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? No

- web UI version: 8.0.1

**To Reproduce**
2. Click on '....' or Run '...'
4. See error (include command output)

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**

**Screenshots**

**Additional context**

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by satterly** [comment]
You've got `ADMIN_USERS=username1, username2` which don't match the username for those API keys ... `user1@example.org`

**Comment by KlavsKlavsen** [comment]
anonymization corrected to match.. if user1 == my login - then I login and am Admin.. If I then move my name to second in the list - I am no longer admin when I login (on new install).

**Comment by satterly** [comment]
There's a space after the comma which can't be good ... https://github.com/alerta/docker-alerta/blob/09e5bd94e3e553426937e6289b2c05e3bd66354a/contrib/kubernetes/helm/alerta/templates/deployment.yaml#L32

**Comment by KlavsKlavsen** [comment]
in alerta web - when logged in as the admin users, and going to "Users" - it only shows my user.
I think the problem is that ldap users are not created - and hence not given rights.. but they should be created - as user1@example.org is (due to cli using it it seems) ?
My login is still my LDAP login - I just get admin rights.. so for user1 everything works as expected.

**Comment by KlavsKlavsen** [comment]
Where's the docs for alertad commands? 
https://docs.alerta.io/en/latest/server.html <- somewhere there I can't find ?
I would like to figure out what "alertad key --user .." does.. as that seems to be the one granting these scopes to an LDAP user.

**Comment by KlavsKlavsen** [comment]
I tried running alertad key.. for the users who do not get setup as admin - but it then just complains they're not admin. If I then add -u user1@example.org - it gives me a key just fine - but no new user in Users list in UI.

**Comment by satterly** [comment]
1. Alerta can not create users in your LDAP server
2. Listing admin users in the `ADMIN_USERS` env var (without spaces) should assign admin privileges to those users
3. If an external auth provider is configured, users will only be created at login time (for storing user preferences etc)

**Comment by KlavsKlavsen** [comment]
and I assume alertad is hardcoded with the --all - to look for ADMIN_USERS env variable? where is that documented? That would be a nice note in the docker-entrypoint script atleast (if I have understood this correctly :)

**Comment by satterly** [comment]
It looks at the `ADMIN_USERS` config setting, which is populated from the `ADMIN_USERS` env variable on Docker.

```
        for admin in current_app.config['ADMIN_USERS']:
            keys = [k for k in ApiKey.find_by_user(admin) if k.scopes == scopes]
```
https://github.com/alerta/alerta/blob/27e5e70df87d3bbb7fa9fa97a469895daebc0229/alerta/commands.py#L86
