### ISSUE TITLE
Docker image size

### ISSUE THREAD

**Issue by anvpetrov** [alerta/docker-alerta#300]
Why image alerta/alerta-web so big ?
It is more then 1.3 Gb
How to reduce size ?

**Comment by satterly** [comment]
I'm not sure what you are talking about. The latest image is 485MB See https://hub.docker.com/layers/alerta/alerta-web/8.5.0/images/sha256-ff659eee5889a676de01e926a5a0504532b7bee17b5dd4ee304186e704467e55?context=explore

**Comment by anvpetrov** [comment]
After pull , image size 1.36 GB
 sudo podman images
REPOSITORY                           TAG              IMAGE ID      CREATED       SIZE
docker.io/alerta/alerta-web          8.5.0            316065fe47be  46 hours ago  **1.36 GB**

**Comment by anvpetrov** [comment]
In my mind microservice must be lightweight.
It's faster download to kubernetes node and safe storage.

In this case, the biggest part is a base image
docker.io/library/python             3.7              9337bc3e7477  10 days ago   900 MB

May be, we can use its slim variant—e.g. python:3.9-slim-buster

**Comment by satterly** [comment]
New image is 500MB smaller.
