### ISSUE TITLE
Outdated IMAGE url on alerta-api for LDAP example

### ISSUE THREAD

**Issue by Shuu-Ri** [alerta/docker-alerta#316]
**Issue Summary**
The IMAGE url for the alerta-api on the docker-compose.yml for LDAP example will returned error message as shown below.
**Docker-Alerta LDAP URL:** https://github.com/alerta/docker-alerta/tree/master/examples/ldap
**Docker-compose url:** https://github.com/alerta/docker-alerta/blob/master/examples/ldap/docker-compose.yml
![image](https://user-images.githubusercontent.com/2571821/126933293-a1be8a44-5be2-49b7-a2cd-9802e8ade169.png)

**Environment**
- OS: Centos
- API version: 8.5.0
- Deployment: Docker

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? No
  (or provide the `/config` endpoint output)  {"endpoint": "http://host.docker.internal:8080"}

**To Reproduce**
1. Add "127.0.0.1 host.docker.internal" onto /etc/hosts.
2. docker login docker.pkg.github.com
3. docker-compose up -d
![image](https://user-images.githubusercontent.com/2571821/126933741-54f67fc1-7e65-4e3c-a830-16f25e4c7abe.png)

**Expected behavior**
Docker pull on the image will success.

**Additional context**

1. After checking through the docker on github, Github mentioned that they had changed the Docker registry to Container registry with the new endpoint **ghcr.io**. 
2. Also, found out the alerta/alerta/alerta-api organization_name/repository no longer existed. It is now at alerta/alerta-api on the ghcr.io. Check screenshot below:
![image](https://user-images.githubusercontent.com/2571821/126934046-d8de3486-d6d3-4228-9fa1-7dca2cecd5a1.png)

**Comment by satterly** [comment]
Thanks. Fixed by https://github.com/alerta/docker-alerta/commit/2365d7382edfd96ab1c3be9715e9db65538ed4c0
