### ISSUE TITLE
Github Authentication and Authorization

### ISSUE THREAD

**Issue by Scott-Phosphore** [alerta/docker-alerta#36]
Hi,

I've set the authentication with Github and it's working with all the users in my organisations. However, none of the Github Users have admin access. We can manage users only in Basic Auth, so I can't change scopes and permissions...
Is there a solution to set all the github's users as admin, or a workaround to be able to log as an admin ?

**Comment by satterly** [comment]
You can map any github org to a set of permissions. For example, user `nfs4` is in the `alerta` organization and there is a permission mapping `alerta` org => `read write admin:alerts admin:keys` ...
<img width="879" alt="screen shot 2017-08-25 at 10 29 11" src="https://user-images.githubusercontent.com/615057/29708687-78d916ee-8981-11e7-9a54-e9a46eeba8c1.png">

So when `nfs4` logs in they get the mapped permissions, not the default `read`...

<img width="672" alt="screen shot 2017-08-25 at 10 29 05" src="https://user-images.githubusercontent.com/615057/29708676-7103fccc-8981-11e7-9775-90d3ef69394f.png">

**Comment by Scott-Phosphore** [comment]
Working perfectly, thanks :)
