### ISSUE TITLE
Why alerta user is member of root group

### ISSUE THREAD

**Issue by whitepiratebaku** [alerta/docker-alerta#445]
Hi team, I see alerta user is member of root group on official docker images, is this a requirement or something can be fixed?

**Comment by satterly** [comment]
There are "test" docker images built for the "alerta-api" where they run as "root" ... https://github.com/alerta/alerta/pkgs/container/alerta-api

The "official" docker images built for docker hub do not run as root. See https://hub.docker.com/r/alerta/alerta-web
