### ISSUE TITLE
How to version docker images?

### ISSUE THREAD

**Issue by satterly** [alerta/docker-alerta#51]
Labels with the Dockerfile ? eg. LABEL version="5.0.8"
Or tags when building on Docker hub?

**Comment by jaxxstorm** [comment]
Did you think more about this? It's hard to do upgrades in Kubernetes without having tags on Docker images

**Comment by satterly** [comment]
@jaxxstorm What tags does kuberntes expect?

**Comment by satterly** [comment]
I use docker hub automated builds which is poorly documented. Looks like this could be the answer though https://stackoverflow.com/a/44796846

**Comment by satterly** [comment]
See “Labelling automated builds on Docker Hub”  https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

**Comment by satterly** [comment]
So I've managed to work out how to add labels ...
```
$ docker inspect 238bfe149be3 | grep -i label
        "MountLabel": "",
        "ProcessLabel": "",
            "Labels": {
                "org.label-schema.build-date": "2018-02-15T17:04:01Z",
                "org.label-schema.schema-version": "1.0.0-rc.1",
                "org.label-schema.url": "http://alerta.io",
                "org.label-schema.vcs-ref": "6dac6ac",
                "org.label-schema.vcs-url": "https://github.com/alerta/docker-alerta"
```
I'm still trying to work out how to add tags using the automated build process on docker hub :(

**Comment by jaxxstorm** [comment]
Generally the best way to do this I've found is to add git tags to your repo, then set it up like this:

![image](https://user-images.githubusercontent.com/1622940/36271509-ab3bb16a-1233-11e8-8424-53990259284b.png)

You might want to consider moving the docker build process into the the main alerta web github repo, under a `docker` folder.

**Comment by jaxxstorm** [comment]
And to answer the previous question, kubernetes doesn't expect any tags, but in order to do upgrades of stuff, you need to have at least versions images (ie 0.x, 0.y) to be able to upgrade to. It can't pull "latest" each time. Anything will help!

**Comment by satterly** [comment]
@jaxxstorm thanks for the suggestion regarding docker hub tags. that's what i thought i might have to do but am reluctant to clutter the core repo with deployment specific files. is there any sensible way to trigger automated builds based on version tags from another repo?

**Comment by jaxxstorm** [comment]
I don't personally know of a way. Some brain dumps:

- As part of the CI pipeline for alerta web, have it git tag this repo with the same tag. You'd need a github token for it, but shouldn't be too hard.
- Have this module be a submodule of alerta web
-

**Comment by satterly** [comment]
I was considering option 1 but what to tag against each time was puzzling me.

**Comment by satterly** [comment]
Some info on using `post_push` hooks ...
https://windsock.io/automated-docker-image-builds-with-multiple-tags/

And an example...
https://github.com/thxCode/rabbitmq-plugins-box

**Comment by satterly** [comment]
```
$ http https://hub.docker.com/v2/repositories/alerta/alerta-web/tags/ | jq '.results[].name'
"5.0.8"
"latest"
```
