### ISSUE TITLE
How is CORS_ORIGINS set?

### ISSUE THREAD

**Issue by jaxxstorm** [alerta/docker-alerta#52]
I'm building a [helm chart](https://helm.sh) for alerta, and I'd like to know how the CORS_ORIGINS are set. It's currently an env var, but I wanna know if it's comma separated or something, so I know if I can loop through it

**Comment by satterly** [comment]
If set as an [environment variable](https://github.com/alerta/alerta/blob/master/alerta/utils/config.py#L90) then yes, it's a comma-separated variable. If set in the [server config file](https://github.com/alerta/alerta/blob/master/alerta/settings.py#L63) it's a python list.

**Comment by jaxxstorm** [comment]
That got it, thanks!

**Comment by jaxxstorm** [comment]
https://github.com/apptio/helmcharts/tree/master/devel/alerta if you're interested
