### ISSUE TITLE
Add CA file(s) for SSL support

### ISSUE THREAD

**Issue by nabadger** [alerta/docker-alerta#60]
Hi, 

I'm using the prometheus-alerta plugin - this lets me ack. alerts from alerta to alerta-manager.

Our alertmanager runs internally on SSL, so we need to provide the CA (I need to make the CA available inside this container).

I can get this working by having something like this in the entrypoint file:

```
# Install certs
if [ ! -z "$(ls -A /certs)" ]; then
  cp /certs/*.crt  /usr/local/share/ca-certificates/ 2>/dev/null
  update-ca-certificates
fi
```
This assumes that the user has mounted their certs into ```/certs/```.

In addition to this we need to set the ca-bundle path for the python requests-lib.

Something like:
```ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt```

The problem I have is that ```ca-update-certificates``` needs to run as root and the container-user is alerta.

I've tried a few workarounds (i.e. run the container as root, but ```su - alerta``` to run the rest of the entrypoint), but these end up rather messy (with multiple permissions issues).

Although I have it working in my fork, I'm running everything as root (which I don't think is right, so don't want to create a PR yet).

Do you have any advice? Not sure if this is something you have dealt with before on this project.

Thanks

**Comment by satterly** [comment]
Looks like you can switch to root, update the CA's and switch back ... 
>Q. I'm extending the node-red docker image which (currently) bases itself on the node:6docker image. I would like to add a custom SSL-Certificate into the docker-image's certificate store.

>A. Why not just switch user to root to run the command to add the cert then switch back?
```
FROM nodered/node-red-docker

ADD DigiCertCA.crt /usr/local/share/ca-certificates/
USER root
RUN update-ca-certificates
USER node-red


ADD settings.js /data/settings.js

RUN npm install node-red-contrib-ttn
RUN npm install node-red-contrib-influxdb
RUN npm install node-red-admin
RUN npm install node-red-node-geohash 

CMD ["npm", "start", "--", "--userDir", "/data"]
```

See https://stackoverflow.com/a/47455064
