### ISSUE TITLE
Reverse proxy support with base path is incomplete

### ISSUE THREAD

**Issue by micw** [alerta/docker-alerta#61]
It's not possible to run the docker image behind a reverse proxy on a certain path, e.g. /alerta/. It's possible to set BASE_URL=/alerta/api but that only affects the API.

* The UI is still served from / - that can be workarounded by altering the path on the proxy to remove /alerta from the path
* Resources are loaded relative to the UI, so that's working
* The callback URL for oauth (e.g. for github) if always http(s)://mydomain.com/, so the path part is missing.

**Comment by satterly** [comment]
Fixed in #141
