### ISSUE TITLE
How to share apikeys between containers on docker environment?

### ISSUE THREAD

**Issue by savpek** [alerta/docker-alerta#67]
It seems that there's no supported way to add predefined key as apikey anywhere? Alerta generates keys automatically but i don't get how i can share them between multiple containers, or alternatively is there way to disable apikey authentication or use other kind of authentication on api calls?

Problem is that other container needs access to alerta api, however they don't know apikeys beforehand and creating them and configuring them afterwards outside (like ui and then configure them to containers) isn't really an option since same configuration is deployed multiple times by machine.

**Comment by satterly** [comment]
PR #68 should allow you to do what you want. ie. define an API key in advance using `ADMIN_KEY` environment variable and use it on all containers that require access to the Alerta API. Let me know if you think this will work for you and I'll merge and build a new container on docker hub.

**Comment by savpek** [comment]
Yes that sound just what i needed 👍 Thanks for very fast response!

**Comment by satterly** [comment]
Ok. This should now be available on docker hub. Let me know if there are any problems.
