### ISSUE TITLE
docker-compose fails "ERROR: manifest for alerta/alerta-web:latest not found"

### ISSUE THREAD

**Issue by SubOptimal** [alerta/docker-alerta#71]
Using the example `docker-compose.yml` the coker-compose up` fails with following error message

> ERROR: manifest for alerta/alerta-web:latest not found

Checking on https://hub.docker.com/r/alerta/alerta-web/tags/ shows there is no image with tag `latest`. If the `docker-compose.yml` is amended to 

```
  ...
  web:
    image: alerta/alerta-web:5.2.4
    ports:
  ...
```

the example can be executed.

Not sure if this is either to be changed on `docker-alerta` or on `alerta-web` to provide a docker image with the tag `latest`.

**Comment by satterly** [comment]
This has been fixed so that the most recent build will be tagged with "latest".
