### ISSUE TITLE
Alerta mongo connection defaults to localhost

### ISSUE THREAD

**Issue by killfill** [alerta/docker-alerta#9]
Hi!

Is it my idea, or alertad by default is trying to reach mongo from 'localhost', those linking to a mongo container doesn't actually do anything usefull?

Thanks!!

**Comment by satterly** [comment]
This code was added for linked Docker mongoDB containers... https://github.com/guardian/alerta/blob/master/alerta/app/database.py#L56

Has something changed? Doesn't this work anymore?

**Comment by killfill** [comment]
Hm..

I was actually looking at this:

https://github.com/guardian/alerta/blob/b9b52e3ed7fdf601cba47f9bca592d5173623827/alerta/settings.py#L20

Not sure how does actually alerta reads the mongo host target, but it doesnt seems to be reading the MONGO_HOST env var.

Tryied to specify MONGO_HOST=mongo and its still trying to connect to localhost

**Comment by killfill** [comment]
Aah, sorry i was miss reading that.

Should be MONGO_PORT=tcp://mongo:27017

Thanks!
